name: deploy-manifests

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - run: doctl kubernetes cluster kubeconfig  save 68baf42b-e60c-4906-8e8c-6dff8e33d703
    - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
    
